#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import sys
import urllib.parse
import urllib.request
from datetime import datetime
from pathlib import Path
from typing import List

import concurrent.futures
import time


# =========================
# UTIL FUNCTIONS
# =========================

def parse_questions(file_path: Path) -> List[str]:
    questions = []
    for line in file_path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line:
            continue
        if "Q:" in line:
            questions.append(line.split("Q:", 1)[1].strip())
    return questions


def synthesize_voicerss(text, output_file, lang="en-us", codec="MP3"):
    api_key = "759c79c9515242148848e58daaf0d74c"  # <-- Place your VoiceRSS API key here
    url = "https://api.voicerss.org/"
    params = {
        "key": api_key,
        "hl": lang,
        "src": text,
        "c": codec,
    }

    query = urllib.parse.urlencode(params)
    full_url = f"{url}?{query}"

    try:
        with urllib.request.urlopen(full_url) as response:
            data = response.read()
        if data.startswith(b'ERROR'):
            print(f"VoiceRSS error for text '{text}': {data.decode()}")
            return False
        with open(output_file, "wb") as f:
            f.write(data)
        return True
    except Exception as e:
        print(f"Failed to synthesize audio for '{text}': {e}")
        return False


def find_new_video(result_dir: Path, before_set):
    after = set(result_dir.glob("*.mp4"))
    new_files = list(after - before_set)
    if not new_files:
        raise RuntimeError("No video generated by SadTalker")
    return new_files[0]


def run_sadtalker(
    sadtalker_python,
    sadtalker_dir,
    source_image,
    audio_path,
    result_dir,
    use_cpu,
    use_still,
    preprocess,
):
    inference_py = sadtalker_dir / "inference.py"

    if not inference_py.exists():
        raise FileNotFoundError("SadTalker inference.py not found")

    result_dir.mkdir(parents=True, exist_ok=True)
    before = set(result_dir.glob("*.mp4"))

    cmd = [
        sadtalker_python,
        str(inference_py),
        "--driven_audio",
        str(audio_path),
        "--source_image",
        str(source_image),
        "--result_dir",
        str(result_dir),
        "--preprocess",
        preprocess,
    ]

    if use_still:
        cmd.append("--still")
    if use_cpu:
        cmd.append("--cpu")

    process = subprocess.run(cmd, cwd=sadtalker_dir)

    if process.returncode != 0:
        raise RuntimeError("SadTalker failed")

    return find_new_video(result_dir, before)


def build_sequence(items: List[dict], static_image: str):
    sequence = []
    for i, item in enumerate(items):
        sequence.append({
            "type": "video",
            "video": item["video_file"],
            "audio": item["audio_file"],
        })
        if i < len(items) - 1:
            sequence.append({"type": "image", "image": static_image})
    return sequence


def load_audio_only_items(audio_dir: Path, limit: int):
    files = sorted([p for p in audio_dir.glob("*") if p.suffix in [".mp3", ".wav"]])
    if limit > 0:
        files = files[:limit]

    items = []
    for i, f in enumerate(files, 1):
        items.append({
            "index": i,
            "qid": f"q{i:03d}",
            "question": f"Question {i}",
            "audio_path": f,
        })
    return items


# =========================
# WORKER FUNCTION
# =========================

def process_item(item, args_dict):
    idx = item["index"]
    qid = item["qid"]
    question = item["question"]
    audio_file = Path(item["audio_path"]).resolve()

    print(f"[{idx}/{args_dict['total']}] {question}")

    # Only generate audio in this phase
    print("Generating audio...")
    success = synthesize_voicerss(
        question,
        audio_file,
        args_dict["voice_lang"],
        args_dict["voice_codec"],
    )
    if not success:
        print(f"Skipping video for {qid} due to audio generation failure.")
        return None
    return {
        "index": idx,
        "qid": qid,
        "question": question,
        "audio_file": str(audio_file),
        "video_file": None,
    }

def process_video_item(item, args_dict):
    idx = item["index"]
    qid = item["qid"]
    question = item["question"]
    audio_file = Path(item["audio_file"]).resolve()

    video_file = None
    result_dir = (args_dict["video_raw_dir"] / qid).resolve()
    source_image = Path(args_dict["source_image"]).resolve()
    print(f"Running SadTalker with audio: {audio_file}")
    try:
        vid = run_sadtalker(
            args_dict["sadtalker_python"],
            args_dict["sadtalker_dir"],
            source_image,
            audio_file,
            result_dir,
            args_dict["cpu"],
            not args_dict["no_still"],
            args_dict["preprocess"],
        )

        final_video = args_dict["final_video_dir"] / f"video_{idx:03d}.mp4"
        shutil.copy2(vid, final_video)
        video_file = str(final_video)

    except Exception as e:
        if not args_dict["continue_on_video_error"]:
            raise
        print(f"Error: {e}")

    return {
        "index": idx,
        "question": question,
        "audio_file": str(audio_file),
        "video_file": video_file,
    }


# =========================
# MAIN
# =========================

def main():
    parser = argparse.ArgumentParser()

    parser.add_argument("--qa-file", default="qa.txt")
    parser.add_argument("--sadtalker-dir", default="SadTalker")
    parser.add_argument("--source-image", default="face.png")
    # Removed --voice-key argument, API key is now hardcoded

    parser.add_argument("--output-root", default="generated")
    parser.add_argument("--voice-lang", default="en-us")
    parser.add_argument("--voice-codec", default="MP3")

    parser.add_argument("--cpu", action="store_true")
    parser.add_argument("--audio-only", action="store_true")
    parser.add_argument("--limit", type=int, default=0)

    args = parser.parse_args()

    qa_file = Path(args.qa_file)
    sadtalker_dir = Path(args.sadtalker_dir)
    source_image = Path(args.source_image)

    if not qa_file.exists():
        raise FileNotFoundError("QA file missing")

    questions = parse_questions(qa_file)

    if args.limit:
        questions = questions[:args.limit]

    run_dir = Path(args.output_root) / datetime.now().strftime("%Y%m%d_%H%M%S")
    audio_dir = run_dir / "audio"
    video_raw_dir = run_dir / "raw"
    final_video_dir = run_dir / "videos"

    audio_dir.mkdir(parents=True, exist_ok=True)
    video_raw_dir.mkdir(parents=True, exist_ok=True)
    final_video_dir.mkdir(parents=True, exist_ok=True)

    items = []
    for i, q in enumerate(questions, 1):
        items.append({
            "index": i,
            "qid": f"q{i:03d}",
            "question": q,
            "audio_path": (audio_dir / f"q{i:03d}.mp3").resolve(),
        })

    args_dict = {
        # "voice_key" removed, now hardcoded
        "voice_lang": args.voice_lang,
        "voice_codec": args.voice_codec,
        "audio_only": args.audio_only,
        "cpu": args.cpu,
        "no_still": False,
        "preprocess": "crop",
        "continue_on_video_error": True,
        "sadtalker_python": sys.executable,
        "sadtalker_dir": sadtalker_dir,
        "source_image": source_image,
        "video_raw_dir": video_raw_dir,
        "final_video_dir": final_video_dir,
        "source_audio_dir": None,
        "total": len(items),
    }


    # Phase 1: Generate all audio files
    print("\n=== Generating all audio files ===")
    audio_results = []
    with concurrent.futures.ProcessPoolExecutor() as executor:
        futures = [executor.submit(process_item, item, args_dict) for item in items]
        for f in concurrent.futures.as_completed(futures):
            res = f.result()
            if res:
                audio_results.append(res)

    print("All audio files generated. Waiting 1 minute before starting video generation...")
    time.sleep(60)

    # Phase 2: Generate all videos (limit concurrency to avoid resource exhaustion)
    print("\n=== Generating all videos ===")
    video_results = []
    with concurrent.futures.ProcessPoolExecutor(max_workers=3) as executor:
        futures = [executor.submit(process_video_item, item, args_dict) for item in audio_results]
        for f in concurrent.futures.as_completed(futures):
            res = f.result()
            if res:
                video_results.append(res)

    manifest = {
        "created_at": datetime.now().isoformat(),
        "items": video_results,
    }

    (run_dir / "manifest.json").write_text(json.dumps(manifest, indent=2))

    print("\nDONE ✅")
    print(f"Output folder: {run_dir}")


if __name__ == "__main__":
    main()